export default {
  url: {
    apply: 'https://goo.gl/forms/rYP2wJbvx9aVgnOg2',
    mailingList: 'http://eepurl.com/cFOmXH',
    workRequest: 'https://goo.gl/forms/ZmiidAbizEhYDMnG3',
    social: {
      fb: 'https://www.facebook.com/groups/ucladevx/',
      gh: 'https://github.com/ucladevx',
      em: 'mailto:ucladevx@gmail.com',
      yt: 'https://www.youtube.com/channel/UCf4uTKuKJe-Pg3zFRYpfNpA',
    },
  },
  team: {
    year2017: [
      {name: 'Erik Melton', title: 'Developer', image: '/assets/profiles/logo.png', bio: 'In the jungle, the mighty jungle, the developer does not sleep tonight because of all of the coffee consumed.'},
      {name: 'Jayendra Jog', title: 'Developer', image: '/assets/profiles/logo.png', bio: 'I played over a thousand games of tetris over winter break.'},
      {name: 'Jahan Kuruvilla Cherian', title: 'Product Manager', image: '/assets/profiles/logo.png', bio: 'Vim enthusiast, Rails lover, Go proponent, C++ die-hard fan. All I care about is good friends, great code, awesome projects and having one hell of a lit time.'},
      {name: 'Cody Ley-Han', title: 'Developer', image: '/assets/profiles/logo.png', bio: 'Originally from a farm, now sunnny LA. Ukulele playing kid willing to work for chickfila, hoping to make it big some day.'},
      {name: 'Adit Deshpande', title: 'Developer', image: '/assets/profiles/logo.png', bio: 'A bay area native who codes and watches sports. Literally 96% of my life. Interested in machine learning and artificial intelligence and love writing about them on my personal blog. Next goal: Build a machine learning model to auto-create this bio for me.'},
      {name: 'Karen Li ', title: 'Developer', image: '/assets/profiles/logo.png', bio: 'Currently either eating, Yelping, or thinking about food. Canadian born and raised. Likes eating potatoes but not being one; avid runner and snowboarder. Enjoys skateboarding and has only wiped out on Bruinwalk twice.'},
      {name: 'Kevin Wang', title: 'Product Manager', image: '/assets/profiles/logo.png', bio: 'Evangelist of whatever tech he is currently working with. Also does web dev. keys: Cherry MX Blues & Steinway. Secretly trained in the dark arts. Did you ever hear the Tragedy of Darth Plagueis the Wise?...'},
      {name: 'Brandon Liu', title: 'Developer', image: '/assets/profiles/logo.png', bio: 'I enjoy life for a living. Throw in some California burritos and cabeza tacos, sprinkle in some rock climbing and the great outdoors, and that\'s all anyone could ask for.'},
      {name: 'Aditya Raju', title: 'Developer', image: '/assets/profiles/logo.png', bio: 'I like sports. I like the Phoenix Suns. I like turtles and puppies. And I like to learn new things. One of my main goals in life is to become successful, and give back by becoming a high school teacher.'},
      {name: 'Christine Chen', title: 'Developer', image: '/assets/profiles/logo.png', bio: 'Passions are the three f\'s: food, frisbee, and photography. From the bay area and gets boba just for the sole purpose of eating the pearls.'},
      {name: 'Rohan Varma', title: 'Product Manager', image: '/assets/profiles/logo.png', bio: 'Lover of coffee and all things machine learning and product management. Runner turned lifter turned runner again. Big Pink Floyd fan. Once wrote an entire C program without segmentation faults, on the first try.'},
      {name: 'Rishub Kumar', title: 'Developer', image: '/assets/profiles/logo.png', bio: 'Bay Area Native. Shorts and flip flops, can never leave the west coast. Goes to class to code and all I use is python, will scrape anything. Loves to eat, watch sports, and chill.  Go Warriors!'},
      {name: 'Shalini Dangi', title: 'Developer', image: '/assets/profiles/logo.png', bio: 'Born and raised in beautiful Southern California. National Park enthusiast. Die-hard Lakers fan. Avid R&B concert goer.'},
      {name: 'Helen Lee', title: 'Developer', image: '/assets/profiles/logo.png', bio: 'Raised in SoCal and blessed to spend another 4 years here. Handing out trash bags, encoding room keys, coding: it\'s a constant journey of self-discovery.'},
      {name: 'Ankur Papneja', title: 'Developer', image: '/assets/profiles/logo.png', bio: 'Pushes code during the day, lifts weights by night. Grew up in LA watching the Lakers. Claims that caffeine has incredible abilities.'},
      {name: 'Jeffrey Chan', title: 'Developer', image: '/assets/profiles/logo.png', bio: 'LA native patiently waiting for my wings to grow out. The only forces on this planet that can hold me down are gravity, Chipotle, and KBBQ.'},
      {name: 'Ashwin Vivek', title: 'Developer', image: '/assets/profiles/logo.png', bio: 'Has lived around the globe, but still manages to get lost with google maps. Likes tennis, software, and being vegetarian. Currently resides in Hong Kong, where he hopes to find food without meat in it.'},
      {name: 'Jasmine Kim', title: 'Product Manager', image: '/assets/profiles/logo.png', bio: 'Change is the only constant in her life. Geeks out on myer-briggs, classical mythologies, and film scores. A believer in human potential and matcha.'},
      {name: 'Karen Fann', title: 'Developer', image: '/assets/profiles/logo.png', bio: 'A short stack of pancakes but will break your ankles in basketball. Jasmine tea and majestic views keep me happy. Knows every Taylor Swift song by heart.'},
      {name: 'Tanzeela Khan', title: 'Developer', image: '/assets/profiles/logo.png', bio: 'Bay area girl who likes her chocolate 80-90% dark and her musicals 100% captivating. When she\'s not hacking, she\'s hiking.'},
      {name: 'Suyash Saxena', title: 'Developer', image: '/assets/profiles/logo.png', bio: 'Last seen in yellow Crocs, rubber-banded spectacles, notoriously stopping MetroLink Trains en route hackathons and adventures across California.'},
      {name: 'Elton Leong', title: 'Developer', image: '/assets/profiles/logo.png', bio: 'Drinks too much boba and owns too many mechanical keyboards. Currently using a WhiteFox with 65g Zealios.'},
      {name: 'Justin Liu', title: 'Developer', image: '/assets/profiles/logo.png', bio: 'Active Soylent drinker, loves urban exploring and seeing ideas go from pixel to product. Will trade GPA for Muji products. Couldn\'t slide into his own DM\'s if he tried.'},
      {name: 'Nikhil Kansal', title: 'Developer', image: '/assets/profiles/logo.png', bio: 'Not talented enough to be a world-class DJ, but definitely enough to be a software engineer. Loves OneRepublic, Coldplay, St. Lucia, Kygo, CHVRCHES, and the like. Has watched The Office and Parks and Rec three times. Hufflepuff. Whovian. ISFP-A.'},
      {name: 'Jorge Fuentes', title: 'Developer', image: '/assets/profiles/logo.png', bio: 'A lifelong adventurer with a delectable taste for random trivia and quesadillas. Enjoys the struggle of anagonizing over code while listening to melancholy music in the dark. Has yet to give up on his childhood dream of being a ninja.'},
      {name: 'Apurva Panse', title: 'Product Manager', image: '/assets/profiles/logo.png', bio: 'Lover of Greek frozen yogurt, podcasts and tech company cafes. Advocate for equal access to computer science education. Amateur food blogger, experienced coder.'},
      {name: 'Charlotte McGinn', title: 'Developer', image: '/assets/profiles/logo.png', bio: 'Enjoys solving problems with code as much as wielding Copic markers to create crafts. Certain that she will change the world, uncertain of how to go about it. Extroverted introvert, part time Pokémon trainer, and wannabe hipster. Sassy, yet sophisticated.'},
      {name: 'Rohan Kapoor', title: 'Developer', image: '/assets/profiles/logo.png', bio: 'Product Designer from LA. Majoring in Computer Science at UCLA. Loves to skateboard, read books, watch movies, and obviously design.'},
      {name: 'Camille Zhang', title: 'Developer', image: '/assets/profiles/logo.png', bio: '3rd year CS major. Music lover, traveler, spent 4 years of schooling and bar singing in NEW ZEALAND!! Looking into learning more about web development through DevX!'},
      {name: 'Shivam Thapar', title: 'Developer', image: '/assets/profiles/logo.png', bio: 'Code enthusiast who loves his french press a little too much'},
      {name: 'Jesse Cai', title: 'Developer', image: '/assets/profiles/logo.png', bio: 'I\'m a second year CS major.'},
      {name: 'Andy Yu', title: 'Developer', image: '/assets/profiles/logo.png', bio: 'Bookworm, puzzle aficionado,  self-proclaimed full stack developer. Likes Python and four space indents with the same passion as his dislike of RoR. Climber of rocks and sometimes trees. Has a pet houseplant named Auri.'},
      {name: 'Omar Ozgur', title: 'Product Manager', image: '/assets/profiles/logo.png', bio: 'I had my focus set on medical school until I realized that CS is life. I love working with strong teams of individuals across a variety of disciplines to develop awesome projects that change lives. I am also a huge video game fanatic, and love to discuss gameplay and strategy with anyone who will listen.'},
      {name: 'Dmitri Brereton', title: 'Project Manager', image: '/assets/profiles/logo.png', bio: 'Memelord by day, asleep by night. Capable of having a conversation using only pusheen stickers. Boba is the only real dev language.'},
      {name: 'Jerry Li', title: 'Project Manager', image: '/assets/profiles/logo.png', bio: 'Organic machine that transforms food into code. Loves solving fun problems, playing board games & badminton, and learning anime songs on piano. Also a Clippers fan, but that always turns out to be really stressful during playoff time every year.'},
      {name: 'Lawrence Chen', title: 'Developer', image: '/assets/profiles/logo.png', bio: 'Former wannabe baller, actor, and dancer... Current wannabe coder... Future wannabe rapper... It\'s a process. But if anyone ever wants to make an app that helps choreograph a basketball themed Lin-Manuel musical? I\'m your guy.'},
      {name: 'Suhani Ashok', title: 'Developer', image: '/assets/profiles/logo.png', bio: 'Will kill for dogs, avocado and bread. Also likes to design sometimes!'},
      {name: 'Austin Lee', title: 'Developer', image: '/assets/profiles/logo.png', bio: 'I love building cool and useful stuff. Challenges excite me and pursuing opportunities to learn will always be one of my top priorities. You will find me jamming on the guitar, performing at hospitals with my A Cappella group, and hacking with friends.'},
      {name: 'William Shao', image: '/assets/profiles/logo.png', bio: 'Born and raised in the Bay. True Kanye West fan. When not coding, can be found on the basketball court or playing guitar. Loves learning beautiful math and being fed Chinese food, pho, and Cheez-its.'},
      {name: 'Katie Luangkote', title: 'Developer', image: '/assets/profiles/logo.png', bio: 'In North Orange County born and raised. Lover of potatoes in any way, shape, or form. Seinfeld addict and enthusiast.'},
      {name: 'Andrew S Chen', title: 'Developer', image: '/assets/profiles/logo.png', bio: 'Andrew studies psychology and cares a lot about the interface between humans and technology (and everything else). He likes startups and the outdoors. He is currently trying to become better at graphic design.'},
      {name: 'Ram Goli', title: 'Developer', image: '/assets/profiles/logo.png', bio: 'An idealist and sentimentalist. Enjoys dreaming, getting all philosophical up in dis, and talking to new peeps. If needed, can be found outdoors throwing frisbees at other people, or in the kitchen eating LOTS of chocolate. Will also write code if you ask nicely'},
      {name: 'Alex Fong', title: 'Developer', image: '/assets/profiles/logo.png', bio: 'Born in the hella cool capital city of California. He can now be found stumbling his way around the web, waiting for the next fix of ice cream or boba, or looking for the cheapest way to get halfway around the world.'},
      {name: 'Yvonne Chen', title: 'Developer', image: '/assets/profiles/logo.png', bio: 'I like drinking tea.'},
    ]
  }
}
